### ISSUE TITLE
doesn't work on IE 11

### ISSUE THREAD

**Issue by nicecue** [AgentME/react-save-refs#2]
new WeakMap() ->> makes error on IE 11

**Comment by AgentME** [comment]
react-save-refs requires a Map+WeakMap polyfill to work in older browsers. It's mentioned in the readme. (Hmm, maybe I should put that in the readme of react-draggable-list and whatever other projects I have using react-save-refs too. Done.)

**Comment by nicecue** [comment]
hello,

thanks for answering me.

as you mentioned, I added polyfill and everything works fine.

thanks again.











Yongnam Jeong

Cell : +82-10-3443-8873

2017-11-27 16:18 GMT+09:00 Chris Cowan <notifications@github.com>:
